export const journeys = [
  {
    id: "enquiry", label: "An enquiry loses its thread", short: "The first conversation",
    quote: "I replied. They replied. Now I can’t remember what we agreed.",
    before: "A message in your inbox, availability in a calendar, a note to yourself somewhere else. The person waiting for an answer is relying on you to join it all up.",
    after: "An AI assistant could turn a scattered conversation into a clear picture: what the person is asking for, what you have promised and what needs to happen next. Studio gives that understanding somewhere to become useful action.",
    tools: ["Gmail / Outlook", "Studio", "Calendar"],
    steps: [
      { title: "Give the enquiry a place", detail: "Across the enquiries you choose to connect, AI could pick out preferences, unanswered questions and commitments—even when they arrive over several messages. Each point links back to the message it came from.", screen: "A new enquiry", note: "Sam would like an introductory call and can usually manage Thursday afternoons.", action: "Next step: check suitable times", owner: "Connected inbox" },
      { title: "Prepare a useful reply", detail: "An assistant could draft in your tone, drawing on your service information and the conversation so far. Available times come from a calendar check; missing information becomes a question rather than a guess.", screen: "A reply, ready for you", note: "Thanks for getting in touch, Sam. Would Thursday at 2pm suit you for an introductory call?", action: "Your review before sending", owner: "You stay in the conversation" },
      { title: "Keep the commitment visible", detail: "Once a time is agreed, connect the booking and any follow-up to the same person. An unfinished promise has somewhere to live.", screen: "The next step is clear", note: "Introductory call · Thursday, 2pm. Send joining details once the appointment is confirmed.", action: "One thread to pick up again", owner: "Studio + your calendar" },
    ],
    outcome: "Less holding it all in your head. A more considered welcome for the person getting in touch.",
  },
  {
    id: "reschedule", label: "One change, five places to update", short: "When plans change",
    quote: "Moving the appointment takes longer than the conversation about moving it.",
    before: "The appointment changes, but the meeting link, room reservation and reminder still describe the old plan. You work through the list, hoping you haven’t missed anything.",
    after: "Agree the change once, then let a connected workflow carry it through the places that need to know and flag anything that needs your attention.",
    tools: ["Studio", "Calendar", "Zoom", "Email"],
    steps: [
      { title: "Find a workable alternative", detail: "Check the practitioner’s availability, service length and any agreed room or preparation requirements.", screen: "A new appointment time", note: "The appointment needs a new time. Wednesday at 11am fits the example practice’s working rules.", action: "Proposed time · awaiting agreement", owner: "Your practice rules" },
      { title: "See what will change", detail: "Review the appointment, calendar event, meeting details and communication together before the workflow applies the update.", screen: "One change, made visible", note: "Appointment · calendar event · meeting details · confirmation. Four connected steps to check.", action: "Review the plan", owner: "You decide" },
      { title: "Know what actually happened", detail: "See which updates finished and which still need attention. If one of your tools is unavailable, you can see what remains to be done.", screen: "Everything has a status", note: "Appointment updated. Calendar updated. Meeting checked. Confirmation ready for review.", action: "Any unfinished step stays visible", owner: "Oceanheart maintains the connection" },
    ],
    outcome: "A change of plan can stay a small event, with fewer chances for someone to turn up at the wrong time.",
  },
  {
    id: "group", label: "A good group idea never gets started", short: "Make room for an idea",
    quote: "I know what I want to offer. The logistics keep putting me off.",
    before: "Dates, registrations, payment arrangements, joining instructions and resources become a second project before the group has even begun.",
    after: "Describe the group you wish you could run. With AI, Rick can turn that idea into a working registration journey, useful materials and small tools built around your approach. You can try the experience, change your mind and shape it further.",
    tools: ["Studio", "Forms", "Stripe", "Zoom", "Drive"],
    steps: [
      { title: "Shape the offering", detail: "Start with a voice note about the group you imagine. AI could turn it into an outline, draft the invitation and surface practical questions you have not settled yet. We refine it with you until it sounds like your work.", screen: "From idea to a plan", note: "A four-week evening group · eight places · a short welcome conversation · materials between meetings.", action: "A plan you can change", owner: "Your approach, made concrete" },
      { title: "Connect the practical pieces", detail: "Use AI-assisted engineering to build the registration page, connect payments and create the joining journey. Rehearse a late registration, a cancellation and a full group before people depend on it. Change the setup as you learn.", screen: "The pieces fit together", note: "Enquiry → welcome conversation → registration → joining details → approved resources.", action: "Try it as a fictional participant", owner: "Studio + a tailored workflow" },
      { title: "Run the group with a clear view", detail: "See who is registered, what needs preparing and where someone is waiting for a response. You decide how to welcome and support the people in the group.", screen: "Ready for the first evening", note: "Check outstanding registrations, prepare the room and make the welcome materials available.", action: "Your attention goes to the people", owner: "A setup maintained with you" },
    ],
    outcome: "A worthwhile idea gets a route into the world, without you having to become a software project manager.",
  },
  {
    id: "resources", label: "The worksheet doesn’t fit the person", short: "A different way in",
    quote: "The material is useful. Another long PDF isn’t what this person needs.",
    before: "Your knowledge lives in documents and exercises, but the format can get in the way. Making an alternative takes time you rarely have.",
    after: "One piece of your work could become a listenable guide, a visual exercise and an interactive reflection. AI makes it practical to explore those forms with you, so a useful resource can fit more than one way of reading, listening or participating.",
    tools: ["Your documents", "Oceanheart", "Studio"],
    steps: [
      { title: "Start with what you trust", detail: "Choose your own material and the need it should meet. Agree what the adaptation must preserve and what the person should control.", screen: "One exercise, another format", note: "An existing values worksheet, adapted into cards someone can arrange at their own pace.", action: "Practitioner-approved source material", owner: "Your knowledge" },
      { title: "Try a small working version", detail: "AI could help reshape your chosen exercise into plain-language prompts, audio or an interactive tool. Rick builds the experience; you compare it with the source and try it with the people it is for. Their feedback can become a working change.", screen: "A tool you can try", note: "Listen to a prompt. Sort the values cards. Switch to one question at a time. Try a simpler explanation grounded in the same exercise.", action: "Review it together", owner: "Built around the intended use" },
      { title: "Keep the person in control", detail: "Make the resource available through an agreed route. Decide together what is private, what can be shared and whether the exercise needs further refinement.", screen: "Room to use it their way", note: "A person can return to the activity, keep a reflection private, or choose what to bring to the next conversation.", action: "Choice built into the experience", owner: "The client has a say" },
    ],
    outcome: "More ways to participate. Your expertise can take a form that is useful to the person in front of you.",
  },
  {
    id: "capacity", label: "The calendar is full. So are you.", short: "A week you can sustain",
    quote: "There’s a space in the calendar. That doesn’t mean I have the capacity.",
    before: "Preparation, travel, group work and recovery time barely appear in a calendar of appointments. The week fits on screen and feels impossible to live.",
    after: "Ask a practical question: “Could I run a group without adding another evening?” An AI planning assistant could explore arrangements across your calendar, preparation and travel, then show what each option would ask of you.",
    tools: ["Studio", "Calendar", "Your working rules"],
    steps: [
      { title: "Describe your actual week", detail: "Make preparation, breaks and travel part of the picture. You tell us what a sustainable week looks like and which boundaries matter to you.", screen: "Time that deserves a place", note: "Keep Wednesday afternoon for preparation. Leave space after groups. Cluster travel where possible.", action: "Rules supplied by you", owner: "Your capacity matters" },
      { title: "Explore the alternatives", detail: "Describe the change you want in ordinary language. AI could turn it into planning options; a scheduling tool checks each against your hours, travel and protected time. Compare the compromises and ask it to try another approach.", screen: "A week you can examine", note: "Option A keeps every evening free but moves two appointments. Option B keeps those appointments and uses one evening a month. Both preserve Wednesday preparation time.", action: "Compare before changing anything", owner: "A planning aid" },
      { title: "Protect the arrangement", detail: "Use the agreed rules in the booking workflow. Bring exceptions to you with enough context to make a decision.", screen: "A boundary stays visible", note: "This request uses your preparation afternoon. Keep that time protected or make a deliberate exception.", action: "The final choice is yours", owner: "Studio + your calendar" },
    ],
    outcome: "A practice that has room for the person running it, as well as the people coming through the door.",
  },
  {
    id: "leave", label: "Taking a break creates more work", short: "Leave, with less loose work",
    quote: "Before I can switch off, I have to remember every place to tell.",
    before: "Appointments, availability, replies and unfinished promises all need attention. Preparing to be away becomes another reason to put it off.",
    after: "A tailored leave workflow brings the consequences together. Review a plan for your absence, then keep track of the agreed changes across your tools.",
    tools: ["Studio", "Calendar", "Email", "Team workspace"],
    steps: [
      { title: "See what needs attention", detail: "Choose the dates and identify affected appointments, administrative commitments and availability settings.", screen: "A view of your time away", note: "An example absence: 12–16 October. Review affected appointments and any follow-ups due while you are away.", action: "Nothing changes yet", owner: "One place to prepare" },
      { title: "Make a considered plan", detail: "Prepare alternatives and draft communications. Agree any handover with the people involved and share only the necessary information.", screen: "A plan for the practical work", note: "Propose new times. Draft absence replies. Assign agreed administrative tasks. Check what still needs your decision.", action: "Review changes and recipients", owner: "You approve the arrangement" },
      { title: "Know what is settled", detail: "Once you approve the plan, carry the changes through and check the result. See what is settled and what still needs a decision before you leave.", screen: "Ready to step away", note: "Availability updated. Drafts reviewed. Handover agreed. Remaining work clearly identified.", action: "A clearer point to stop", owner: "A maintained workflow" },
    ],
    outcome: "Taking time away becomes something your working setup can support.",
  },
];
