export const journeys = [
  {
    id: "enquiry", label: "An enquiry loses its thread", short: "The first conversation",
    quote: "I replied. They replied. Now I can’t remember what we agreed.",
    before: "A message in your inbox, availability in a calendar, a note to yourself somewhere else. The person waiting for an answer is relying on you to join it all up.",
    after: "An AI assistant could turn a scattered conversation into a clear picture: what the person is asking for, what you have promised and what needs to happen next. Studio gives that understanding somewhere to become useful action.",
    tools: ["Gmail / Outlook", "Studio", "Calendar"],
    steps: [
      { title: "Give the enquiry a place", detail: "Keep your current mailbox. We could teach the workflow to separate new enquiries from other mail, then pick out preferences, unanswered questions and commitments across the thread. Each point links back to its source.", screen: "A new enquiry", note: "Sam would like an introductory call and can usually manage Thursday afternoons.", action: "Next step: check suitable times", owner: "Connected inbox" },
      { title: "Prepare a useful reply", detail: "An assistant could draft in your tone, drawing on your service information and the conversation so far. Available times come from a calendar check; missing information becomes a question rather than a guess.", screen: "A reply, ready for you", note: "Thanks for getting in touch, Sam. Would Thursday at 2pm suit you for an introductory call?", action: "Your review before sending", owner: "You stay in the conversation" },
      { title: "Keep the commitment visible", detail: "Once a time is agreed, connect the booking and any follow-up to the same person. An unfinished promise has somewhere to live.", screen: "The next step is clear", note: "Introductory call · Thursday, 2pm. Send joining details once the appointment is confirmed.", action: "One thread to pick up again", owner: "Studio + your calendar" },
    ],
    outcome: "Less holding it all in your head. A more considered welcome for the person getting in touch.",
  },
  {
    id: "reschedule", label: "One change, five places to update", short: "When plans change",
    quote: "Moving the appointment takes longer than the conversation about moving it.",
    before: "The appointment changes, but the meeting link, room reservation and reminder still describe the old plan. You work through the list, hoping you haven’t missed anything.",
    after: "Agree the change once, then let a connected workflow carry it through the places that need to know and flag anything that needs your attention.",
    tools: ["Studio", "Calendar", "Zoom", "Email"],
    steps: [
      { title: "Find a workable alternative", detail: "Check the practitioner’s availability, service length and any agreed room or preparation requirements.", screen: "A new appointment time", note: "The appointment needs a new time. Wednesday at 11am fits the example practice’s working rules.", action: "Proposed time · awaiting agreement", owner: "Your practice rules" },
      { title: "See what will change", detail: "Review the appointment, calendar event, meeting details and communication together before the workflow applies the update.", screen: "One change, made visible", note: "Appointment · calendar event · meeting details · confirmation. Four connected steps to check.", action: "Review the plan", owner: "You decide" },
      { title: "Know what actually happened", detail: "See which updates finished and which still need attention. If one of your tools is unavailable, you can see what remains to be done.", screen: "Everything has a status", note: "Appointment updated. Calendar updated. Meeting checked. Confirmation ready for review.", action: "Any unfinished step stays visible", owner: "Oceanheart maintains the connection" },
    ],
    outcome: "A change of plan can stay a small event, with fewer chances for someone to turn up at the wrong time.",
  },
  {
    id: "invoices", label: "The sessions are done. The invoices aren’t.", short: "Sessions and invoices",
    quote: "I lose an evening working out what to invoice.",
    before: "Session dates are in one place, agreed rates in another. Cancellations, prepaid blocks and the invoices you already sent all need checking before the numbers make sense.",
    after: "An agent could prepare the invoice from your records and billing instructions, with each line linked to its source. Rick tests the rules and exceptions with you, so missing information becomes a question you can answer.",
    tools: ["Session records", "Your billing rules", "Studio", "Accounting tools"],
    steps: [
      { title: "Give it the right context", detail: "Bring together confirmed attendance, agreed rates, cancellation rules and previous invoices. A calendar entry alone does not mean a session took place.", screen: "Ready to reconcile", note: "Two attended sessions at £80 each. One session with attendance still to confirm. One session already invoiced.", action: "Ask about the incomplete record", owner: "Your records and instructions" },
      { title: "Prepare the invoice", detail: "The workflow checks which sessions are billable and calculates the amounts from the agreed rules. You can inspect the source of each line and correct an assumption.", screen: "A draft with its working", note: "Two confirmed, uninvoiced sessions: £160. The already invoiced session is excluded. The unconfirmed session stays open for your attention.", action: "Draft prepared for review", owner: "A traceable result" },
      { title: "Make it fit your practice", detail: "Tell Rick what needs to work differently. Test a prepaid session, a cancellation or a rate change against your examples before using the updated workflow.", screen: "Your rules, refined", note: "From October, use £90 for new agreements. Keep existing clients on their agreed rate. Check both cases together.", action: "A tested change to your setup", owner: "Maintained with you" },
    ],
    outcome: "Less time reconstructing the month. A prepared invoice you can understand and check.",
  },
  {
    id: "knowledge", label: "Which version of that document is current?", short: "Your practice knowledge",
    quote: "I know I wrote it down. I just can’t find the right version.",
    before: "Policies, service details and useful answers are spread across folders and old documents. Finding the information is one task; checking that it still applies is another.",
    after: "A knowledge assistant could answer from the practice material you choose, with links to the sources. Rick helps organise the context and test what happens when a document changes or an answer is missing.",
    tools: ["Your documents", "Drive / OneDrive", "Studio"],
    steps: [
      { title: "Choose the sources", detail: "Identify the current documents and the ones they replace. Agree which material the assistant should use and who should be able to see it.", screen: "A clear source of information", note: "Current cancellation policy selected. Last year’s version kept as history, excluded from current answers.", action: "Your approved practice material", owner: "Context chosen with you" },
      { title: "Ask a practical question", detail: "The assistant could find the relevant passage and show it alongside the answer. If the sources disagree or do not answer the question, it should make that clear.", screen: "An answer you can check", note: "What notice do I ask for? The answer links to the current policy and the paragraph that supports it.", action: "Open the supporting source", owner: "Evidence beside the answer" },
      { title: "Keep the answers useful", detail: "When your policy changes, update the source and try the questions again. Rick can investigate a poor answer and adjust the instructions or the way information is found.", screen: "A change carried through", note: "The revised policy is now used. Previous answers retain a record of the version they relied on.", action: "Check the new answer together", owner: "An assistant maintained over time" },
    ],
    outcome: "Less hunting through folders. Your own practice knowledge, easier to use.",
  },
  {
    id: "capacity", label: "The calendar is full. So are you.", short: "A week you can sustain",
    quote: "There’s a space in the calendar. That doesn’t mean I have the capacity.",
    before: "Preparation, travel, administrative work and recovery time barely appear in a calendar of appointments. The week fits on screen and feels impossible to live.",
    after: "Ask a practical question: “Could I take on another client without adding another evening?” An AI planning assistant could explore arrangements across your calendar, preparation and travel, then show what each option would ask of you.",
    tools: ["Studio", "Calendar", "Your working rules"],
    steps: [
      { title: "Describe your actual week", detail: "Make preparation, breaks and travel part of the picture. You tell us what a sustainable week looks like and which boundaries matter to you.", screen: "Time that deserves a place", note: "Keep Wednesday afternoon for preparation. Leave space between sessions. Cluster travel where possible.", action: "Rules supplied by you", owner: "Your capacity matters" },
      { title: "Explore the alternatives", detail: "Describe the change you want in ordinary language. AI could turn it into planning options; a scheduling tool checks each against your hours, travel and protected time. Compare the compromises and ask it to try another approach.", screen: "A week you can examine", note: "Option A keeps every evening free but moves two appointments. Option B keeps those appointments and uses one evening a month. Both preserve Wednesday preparation time.", action: "Compare before changing anything", owner: "A planning aid" },
      { title: "Protect the arrangement", detail: "Use the agreed rules in the booking workflow. Bring exceptions to you with enough context to make a decision.", screen: "A boundary stays visible", note: "This request uses your preparation afternoon. Keep that time protected or make a deliberate exception.", action: "The final choice is yours", owner: "Studio + your calendar" },
    ],
    outcome: "A practice that has room for the person running it, as well as the people coming through the door.",
  },
  {
    id: "leave", label: "Taking a break creates more work", short: "Leave, with less loose work",
    quote: "Before I can switch off, I have to remember every place to tell.",
    before: "Appointments, availability, replies and unfinished promises all need attention. Preparing to be away becomes another reason to put it off.",
    after: "A tailored leave workflow brings the consequences together. Review a plan for your absence, then keep track of the agreed changes across your tools.",
    tools: ["Studio", "Calendar", "Email", "Your working rules"],
    steps: [
      { title: "See what needs attention", detail: "Choose the dates and identify affected appointments, administrative commitments and availability settings.", screen: "A view of your time away", note: "An example absence: 12–16 October. Review affected appointments and any follow-ups due while you are away.", action: "Nothing changes yet", owner: "One place to prepare" },
      { title: "Make a considered plan", detail: "Prepare alternatives and draft communications. Identify what can wait until you return and what needs attention before you go.", screen: "A plan for the practical work", note: "Propose new times. Draft absence replies. Set aside follow-ups for your return. Check what still needs your decision.", action: "Review changes and recipients", owner: "You approve the arrangement" },
      { title: "Know what is settled", detail: "Once you approve the plan, carry the changes through and check the result. See what is settled and what still needs a decision before you leave.", screen: "Ready to step away", note: "Availability updated. Drafts reviewed. Follow-ups organised. Remaining work clearly identified.", action: "A clearer point to stop", owner: "A maintained workflow" },
    ],
    outcome: "Taking time away becomes something your working setup can support.",
  },
];
