import { EditorialPage, ReadingSection } from '../components/editorial';
import Link from '../components/site-link';
export const metadata = { title: 'The practice | Oceanheart', description: 'An integrative practice centred on your lived experience and how you relate to it.', alternates: { canonical: 'https://www.oceanheart.ai/practice' } };
export default function Page() { return <EditorialPage tone="human" label="The practice" title="One inquiry. Many ways in." intro="An integrative practice centred on your lived experience and how you relate to it." invitation="Find out whether this feels right for you." bookingKinds={['exploration']}>
<ReadingSection label="What guides the work"><p>We attend to what is happening for you in the session: a thought, a feeling, a sensation, or the way you find yourself responding. We might talk about the past, while noticing how that experience is present now.</p><p>My guiding question is whether there is room around and within an experience, or whether you feel tightly caught inside it. We explore that together, without needing to force a particular result.</p></ReadingSection>
<ReadingSection label="Conversation & ACT"><p>Acceptance and Commitment Therapy informs how we explore thoughts, feelings, the stories you carry about yourself and what matters to you. Conversation can help us notice your relationship with an experience and consider how you want to respond.</p><Link className="depth-next" href="/act">More about ACT</Link></ReadingSection>
<ReadingSection label="Breath & somatic inquiry"><p>We may bring attention to breathing, sensation, posture or an impulse to move. Somatic inquiry means becoming curious about your felt experience as it is happening, and giving you room to describe it in your own terms.</p><p>At times the invitation may be to explore more closely; at others, to ease back, rest or find something steadying. Changes in sensation or emotion can happen, but release is never something you have to produce.</p><Link className="depth-next" href="/breathwork">More about breathwork</Link></ReadingSection>
<ReadingSection label="Hands-on work"><p>Massage and touch can be part of the work where appropriate and explicitly agreed. We discuss what that would involve before beginning, and you can change your mind. A session can also remain entirely conversational.</p><Link className="depth-next" href="/deep-tissue-massage">Standalone massage</Link></ReadingSection>
<ReadingSection label="A practice shaped with you"><p>These are possibilities within the work, rather than a sequence everyone goes through. We choose what is useful together, and make time to step back, understand where we are and consider where to go next.</p></ReadingSection>
</EditorialPage>; }
