import { EditorialPage, ReadingSection } from '../components/editorial';
import Link from '../components/site-link';
export const metadata = { title: 'About Rick | Oceanheart', description: 'Therapeutic work grounded in psychological training, lived inquiry and contemplative practice.', alternates: { canonical: 'https://www.oceanheart.ai/about' } };
export default function Page() { return <EditorialPage portrait="/images/rick-portrait-looking-left-v2.png" tone="human" label="About Rick" title="A life spent asking." intro="Therapeutic work grounded in psychological training, lived inquiry and contemplative practice." invitation="Bring your questions." bookingKinds={['exploration']}>
<ReadingSection label="What brings me to this work"><p>In my own life, freedom has been connected with seeing the nature of things clearly and letting go of ideas about who I imagine myself to be.</p><p>I am interested in how we meet what is happening: whether there is room to feel and respond, or a sense of being tightly contained within an experience.</p></ReadingSection>
<ReadingSection label="Training & experience"><p>My background includes cognitive behavioural therapy in NHS and private practice. I hold a postgraduate diploma in Cognitive Behavioural Therapy from Royal Holloway, a postgraduate certificate in Primary Mental Healthcare from the University of Central Lancashire, and a BSc in Psychology from UWE Bristol.</p><p>I travel deep with CBT, but I’m no longer BABCP-accredited. This is a conscious choice to make room for what I feel is a less conventional but more effective edge.</p></ReadingSection>
<ReadingSection label="Contemplative practice"><p>I have maintained a contemplative practice for twenty years, within and outside the Rinzai and Soto Zen traditions. Within Zenways, led by Daizan Roshi, I am a junior Zen teacher in training.</p><p>Scientific thinking and spiritual inquiry both matter to me. I bring curiosity about meaning, identity and lived experience, while leaving room for your own language and worldview.</p></ReadingSection>
<ReadingSection label="A researcher-practitioner orientation"><p>I learn through study, personal practice and working with people. I am drawn to the meeting points between psychology, the body, contemplative traditions and storytelling.</p><p>My interests for further study include anatomy, breathwork, neuroscience and mythology. These are directions for ongoing learning, rather than additional qualifications or claims of specialist expertise.</p></ReadingSection>
<ReadingSection label="Technology in the background"><p>My engineering experience and work with AI inform how I learn, explore ideas and organise my work. My aim is to keep more attention available for the person in front of me and to support an affordable, sustainable practice.</p><p>Technology is part of that wider working life. It is not a requirement for taking part in a session.</p></ReadingSection>
</EditorialPage>; }
