import type { Metadata } from 'next';
import { EditorialPage, ReadingSection } from '../components/editorial';
export const metadata: Metadata = { title: "ACT — Acceptance & Commitment Therapy | Oceanheart", description: "A space to explore what you’re finding difficult, what matters to you, and the steps you want to take in your life.", alternates: { canonical: 'https://www.oceanheart.ai/act' } };
export default function Page() { return <EditorialPage tone="human" image="/images/kai-looking-left.png" label="Acceptance & Commitment Therapy" title="Make space for what matters." intro="A space to explore what you’re finding difficult, what matters to you, and the steps you want to take in your life." bookingKinds={["therapy", "exploration"]} invitation="We can start with what’s here." bookingDescription="Book a therapeutic session or begin with a free exploration conversation.">
<ReadingSection label="What is ACT?"><p>Acceptance and Commitment Therapy brings together mindful attention, openness to thoughts and feelings, and action guided by your values. The focus is developing more flexibility in how you respond to your experience.</p><p>We can explore what matters to you and what a meaningful next step might look like in everyday life.</p></ReadingSection>
<ReadingSection label="Working together"><p>You might bring a particular difficulty, a recurring pattern, or a sense of feeling stuck. We’ll take time to understand your experience and agree what to focus on.</p><p>ACT informs my integrative therapeutic practice. Sessions are shaped around you, with space for conversation and reflection.</p></ReadingSection>
<ReadingSection label="My background"><p>My background includes cognitive behavioural therapy in NHS and private practice. I trained in CBT and am no longer BABCP-accredited. This is my own integrative practice.</p></ReadingSection>
<ReadingSection label="Arranging a session"><p>Therapeutic sessions are currently £35 per hour. We’ll agree the session length, location and format when arranging your booking. A short exploration conversation is free.</p></ReadingSection>
<ReadingSection label="Further reading"><p><a href="https://contextualscience.org/act">Learn more about ACT from the Association for Contextual Behavioral Science.</a></p></ReadingSection>
</EditorialPage>; }
