import { EditorialPage, ReadingSection } from '../components/editorial';
import Link from '../components/site-link';
export const metadata = { title: 'Sessions | Oceanheart', description: 'Individual sessions shaped with you, with choice about the focus, pace and ways of working.', alternates: { canonical: 'https://www.oceanheart.ai/sessions' } };
export default function Page() { return <EditorialPage tone="human" label="Sessions" title="We begin where you are." intro="Individual sessions shaped with you, with choice about the focus, pace and ways of working." invitation="Start with a conversation." bookingKinds={['exploration']}>
<ReadingSection label="A first conversation"><p>We begin with what brings you here and what you hope for. You can ask about my approach, discuss what you feel comfortable with and decide whether you want to work together. You do not need to send a detailed personal history in your first email.</p></ReadingSection>
<ReadingSection label="During a session"><p>We might follow a conversation, pause to notice what is happening in your body, or explore an invitation involving breath or movement. We may spend time with a difficult experience, or give more attention to lightness, relaxation and finding your footing.</p><p>There is no requirement to revisit your past or work with touch. We agree the focus together.</p></ReadingSection>
<ReadingSection label="Your choice stays present"><p>I explain invitations and check how the work is landing. You can say no, ask for a different approach, take a break or stop. We periodically step back to reflect on what we are doing and where it might be going.</p></ReadingSection>
<ReadingSection label="Time & practicalities"><p>Individual therapeutic sessions are currently £35 per hour. We confirm length, location and format before booking. Any plans for hands-on work are discussed and agreed beforehand.</p><p>A short exploration conversation is free. Standalone massage can also be arranged separately.</p></ReadingSection>
</EditorialPage>; }
