export type Example = {label:string; kind:'product'|'reply'|'social'|'enquiry'; brief:string; facts:string[]; headline:string; text:string; check:string; fictional?:boolean;};
export type Study = {slug:string; name:string; short:string; place:string; sector:string; number:string; title:string; intro:string; line:string; description:string; art:string; reference:string; referenceAlt:string; source:string; sourceLabel:string; palette:string; examples:Example[]; lesson:string;};
export const studies:Study[]=[
 {slug:'carve',name:'Carve Coffee Roasters',short:'Carve',place:'Shore Road, Swanage',sector:'Coffee · Retail · Hospitality',number:'01',title:'Good coffee.\nMore ways\nto tell its story.',intro:'A bag of coffee already holds a story. A practical AI session could help turn the facts into a shop card, a social post and a thoughtful customer reply.',line:'From the bag to the next conversation.',description:'An independent study using Carve’s public coffee listing and visual identity. A recognisable product becomes the starting point for work an owner can learn to do themselves.',art:'carve-campaign.webp',reference:'carve-coffee-reference.webp',referenceAlt:'Actual Carve Tanzania coffee bag from the Carve website',source:'https://www.carvecoffee.co.uk/',sourceLabel:'Carve’s website and Tanzania coffee listing',palette:'Ink / sea / burnt orange',lesson:'One product, several useful formats. Learn to keep the facts consistent while changing the voice and shape of the copy.',examples:[
 {label:'A product card',kind:'product',brief:'Make a short counter card from the details on this coffee. Keep the origin, process and tasting notes accurate. Don’t invent a story about the grower.',facts:['Tanzania · Ngila','Washed process · SL28','Black tea, honey, dried fruits','Suitable for espresso and filter'],headline:'A little Tanzania.\nA Dorset morning.',text:'Carve’s Tanzania single origin brings notes of black tea, honey and dried fruits to your cup. A washed coffee from Ngila, ready to explore through espresso or filter.',check:'Compare every origin and tasting detail with the current bag. Confirm availability before using the card.'},
 {label:'A review reply',kind:'reply',fictional:true,brief:'Practice review: “Lovely coffee by the sea. I bought a bag but I’m not sure how to brew it at home.” Draft a warm reply without assuming what equipment they have.',facts:['Fictional training review','No customer name or rating','Draft only; a person sends it'],headline:'A reply that opens\na useful conversation.',text:'Thanks for stopping by and taking a bag home. What do you use to make your coffee? Let us know the coffee and your brewing method, and we can help you find a starting point.',check:'Check that the team can offer this help. This is an invented practice review, not a real Google review or an endorsement.'},
 {label:'A social post',kind:'social',brief:'Write a short caption about taking a bag of Carve coffee home after visiting Swanage. Keep it relaxed. Use the supplied product facts and avoid discounts or claims about stock.',facts:['Independent Dorset roaster','Beach café on Shore Road','Coffee for home as well as the café'],headline:'Take a little\nof the morning home.',text:'Coffee by the sea, then coffee at your own kitchen table. Explore Carve’s coffee for home and find a bag for your next slow morning.',check:'Confirm the linked product is available and that the final wording sounds like the team.'}
 ]},
 {slug:'tied',name:'Tied',short:'Tied',place:'62 High Street, Swanage',sector:'Flowers · Gifts · Events',number:'02',title:'Let the flowers\nstart the\nconversation.',intro:'An arrangement, a few notes and a clear intention. Explore how a florist could use AI to shape a seasonal graphic or get a useful first reply onto the page.',line:'A little less staring at a blank page.',description:'An independent study inspired by the seasonal flowers and interior photography on Tied’s website. Botanical collage makes the material feel as personal as the work.',art:'tied-campaign.webp',reference:'tied-shop-reference.webp',referenceAlt:'Flower display and wooden counter photographed for Tied’s website',source:'https://www.tied.florist/',sourceLabel:'Tied’s website and floral photography',palette:'Plum / lilac / botanical green',lesson:'Start from your own materials and voice. Learn to brief a visual, shape the wording and check what the image actually promises.',examples:[
 {label:'A seasonal graphic',kind:'social',brief:'Create a quiet, inviting seasonal message for Tied. Use the real floral photography as the reference. Don’t announce a new range, price or delivery promise.',facts:['Flowers from a Swanage shop','Seasonal stems','Gifts, weddings and events'],headline:'For someone.\nFor something.\nJust because.',text:'Seasonal flowers, thoughtfully put together. A little colour for a familiar room, or something to say what words don’t quite manage.',check:'This is concept artwork, not an arrangement offered for sale. Choose an available bouquet and approve the wording before publishing.'},
 {label:'A wedding enquiry',kind:'enquiry',fictional:true,brief:'Practice enquiry: “We’re getting married near Swanage and love your flowers. Where do we start?” Ask for the details needed for a conversation without promising availability.',facts:['Fictional practice enquiry','Date and venue unknown','No price or availability assumed'],headline:'A thoughtful\nfirst reply.',text:'Thank you for thinking of Tied for your wedding flowers. Could you share your date and venue, along with a little about what you’re imagining? Any colours, photographs or an approximate budget would give us a helpful starting point for a conversation.',check:'The florist checks availability, location, scope and tone. Nothing is booked or priced by this example.'},
 {label:'A shop description',kind:'product',brief:'Draft a short introduction for a local directory. Use the public website. Keep it factual and avoid repeating awards or opening times that could change.',facts:['62 High Street, Swanage','Seasonal flowers and plants','Cards and gifts','Wedding and event flowers'],headline:'A small shop.\nA thoughtful gesture.',text:'Tied is a florist on Swanage’s High Street, with seasonal flowers, plants, cards and gifts. The shop also creates flowers for weddings and events.',check:'Verify the current services and wording with the business before using the description anywhere.'}
 ]},
 {slug:'salt-pig',name:'The Salt Pig Too',short:'The Salt Pig',place:'7A Station Road, Swanage',sector:'Food · Farm shop · Restaurant',number:'03',title:'A changing counter.\nA fresh story\nevery day.',intro:'When the food changes, the words need to catch up. A practical session could turn confirmed notes into a clear update, or help the team reply to a group enquiry.',line:'Good ingredients for the next piece of work.',description:'An independent study grounded in The Salt Pig Too’s Swanage page and fish-counter photography. A bold food print gives the local produce a different kind of presence.',art:'salt-pig-campaign.webp',reference:'salt-pig-swanage-reference.webp',referenceAlt:'The Salt Pig Too Swanage fish counter, from the business’s website',source:'https://www.thesaltpig.co.uk/salt-pig-too-swanage/',sourceLabel:'The Salt Pig Too’s official Swanage page',palette:'Charcoal / chartreuse / paper',lesson:'Keep changing details in the source notes. Learn to turn those notes into drafts without letting the tool invent today’s menu or make a booking.',examples:[
 {label:'A shop introduction',kind:'product',brief:'Make a compact introduction using the public Swanage page. Explain that it is a café, restaurant, farm shop and butchery. Don’t invent a daily special or price.',facts:['Café and restaurant','Farm shop and butchery','Station Road, Swanage','Purbeck and Dorset food'],headline:'Something for\nthe table.',text:'A café, restaurant, farm shop and butchery in the heart of Swanage. Explore The Salt Pig Too’s counter and its connection to Purbeck and Dorset food.',check:'The business approves the description. Current menus and availability always come from the team.'},
 {label:'A group enquiry',kind:'enquiry',fictional:true,brief:'Practice enquiry: “Could we bring a group of 12 for dinner?” Ask for a date and explain the next step using the website’s guidance for groups over 10. Don’t confirm a table.',facts:['Fictional practice enquiry','12 people','Date not supplied','Website directs groups of 10+ to call'],headline:'A clear next step.\nNo guessed booking.',text:'Thanks for thinking of us for your group dinner. Which date did you have in mind? For a group of 12, please call the restaurant so the team can talk through availability and arrangements with you.',check:'Confirm the current group-booking policy. A person handles availability, dietary requirements and any booking.'},
 {label:'A local update',kind:'social',brief:'Write a short, inviting post about the Swanage location. Use its mix of café, restaurant and farm shop. Avoid claims about today’s food, provenance of individual items or opening hours.',facts:['Swanage location','Coffee and food','Farm-shop counter'],headline:'Call in.\nSee what’s good.',text:'A coffee stop, a bite to eat, something for home. Find The Salt Pig Too on Station Road in Swanage and see what’s on the counter.',check:'Pair with a current, accurate photograph. The generated image here is an artistic study, not a record of today’s counter.'}
 ]},
];
export const studyPath=(slug:string)=>`/small-business/swanage/${slug}`;
