import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { buildCatalog, therapyOpsRoot } from "./catalog-lib.mjs";

const catalog = await buildCatalog();
const outputPath = path.join(
  therapyOpsRoot,
  "apps-script",
  "src",
  "GeneratedCatalog.gs",
);

const serializedCatalog = JSON.stringify(catalog);
const generatedSource = [
  "// Generated by scripts/build-catalog.mjs.",
  "// Edit config, copy, forms, or schemas and rebuild instead.",
  "",
  `var THERAPY_OPS_CATALOG = JSON.parse(${JSON.stringify(serializedCatalog)});`,
  "",
].join("\n");

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, generatedSource, "utf8");
process.stdout.write(
  `Generated ${path.relative(therapyOpsRoot, outputPath)} ` +
    `for ${catalog.service.copyVersion}.\n`,
);
